### ISSUE TITLE
Can't download and apply YAML custom schema

### ISSUE THREAD

**Issue by dawilliams** [neoclide/coc-yaml#9]
```
Versions
vim version: NVIM v0.4.3
node version: v13.7.0
coc.nvim version: 0.0.74-6700e7468d
term: iTerm.app
platform: darwin
```
Hello,
I can't get coc to registrar the custom schema. My coc-settings.json has the following...
```
{
...
"yaml.schemas": {
      "http://json.schemastore.org/drone": "*"
    },
...
}
```

I can see the following config in the logs
```
[Trace - 10:25:54 AM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "execArgv": [],
            "trace": {
                "server": "verbose"
            },
            "schemas": {
                "http://json.schemastore.org/drone": "*"
            },
            "format": {
                "enable": false,
                "singleQuote": false,
                "bracketSpacing": true,
                "proseWrap": "preserve"
            },
            "validate": true,
            "hover": true,
            "completion": true,
            "customTags": []
        },
        "http": {
            "proxyStrictSSL": true
        }
    }
}
``` 
but I see no change in behavior and have the following in the logs...
```
[Trace - 10:25:54 AM] Sending notification 'json/schemaAssociations'.
Params: {}


[Trace - 10:25:54 AM] Sending notification 'yaml/registerCustomSchemaRequest'.
No parameters provided.


[Trace - 10:25:54 AM] Received request 'custom/schema/request - (0)'.
Params: "file:///Users/davidwilliams/git/api-gateway/.drone.yml"


[Trace - 10:25:54 AM] Sending response 'custom/schema/request - (0)'. Processing request took 0ms
No result returned.
```
Am I missing something? Thank you for your help!

**Comment by maulanakmal** [comment]
I have have the same problem

**Comment by chemzqm** [comment]
Should be problem of yaml language server, can't reproduce.

**Comment by chemzqm** [comment]
Fixed on latest coc-yaml.

**Comment by kwrobert** [comment]
I'm using the latest coc-yaml (version 1.3.0), and I'm still having this issue. The yaml relevant portion of my config looks like this:

```
  "yaml.schemaStore.enable": true,
  "yaml.trace.server": "verbose",
  "yaml.schemas": {
    "https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/main/service-schema.json": "/*azure*pipeline*.y*ml"
  }
```

and I get the same sort of API responses: 

```
[Trace - 6:55:50 AM] Received response 'initialize - (0)' in 439ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "completionProvider": {
            "resolveProvider": false
        },
        "hoverProvider": true,
        "documentSymbolProvider": true,
        "documentFormattingProvider": false,
        "documentRangeFormattingProvider": false,
        "documentLinkProvider": {},
        "workspace": {
            "workspaceFolders": {
                "changeNotifications": true,
                "supported": true
            }
        }
    }
}


[Trace - 6:55:50 AM] Sending notification 'initialized'.
Params: {}


[Trace - 6:55:50 AM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "execArgv": [],
            "trace": {
                "server": "verbose"
            },
            "schemas": {
                "https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/main/service-schema.json": "/*azure*pipeline*.y*ml"
            },
            "format": {
                "enable": false,
                "singleQuote": false,
                "bracketSpacing": true,
                "proseWrap": "preserve",
                "printWidth": 80
            },
            "validate": true,
            "hover": true,
            "completion": true,
            "customTags": [],
            "schemaStore": {
                "enable": true
            }
        },
        "http": {
            "proxyStrictSSL": true
        },
        "[yaml]": {}
    }
}


[Trace - 6:55:50 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/kyle/Worldcom%20Exchange%20Inc/Parexel%20-%20Ansible%20Project%201839/paraxel_lab_ansible/azure-pipelines.yml",
        "languageId": "yaml",
        "version": 1,
        "text": "trigger:\n# - main\n- none\n\nvariables:\n  - name: build_id\n    value: $(Build.BuildNumber)\n\npool:\n  # Use this for Microsoft self hosted agents\n  # vmImage: 'ubuntu-latest'\n  name: Default\n  demands: agent.os -equals Linux\n\nstages:\n- stage: DeployIaaS\n  jobs:\n  - job: DeployLinuxVMs\n    steps:\n    - task: AzureResourceManagerTemplateDeployment@3\n      displayName: Deploy Linux VM from ARM Template\n      inputs:\n        deploymentScope: 'Resource Group'\n        azureResourceManagerConnection: 'Kyle Lab Azure Subscription (eb84bcb5-ea3b-4d85-aa65-3a076739a8b2)'\n        subscriptionId: 'eb84bcb5-ea3b-4d85-aa65-3a076739a8b2'\n        action: 'Create Or Update Resource Group'\n        resourceGroupName: 'pipeline-rg'\n        location: 'East US'\n        templateLocation: 'Linked artifact'\n        csmFile: 'azure/arm_templates/101-vm-simple-linux/azuredeploy.json'\n        csmParametersFile: 'azure/arm_templates/101-vm-simple-linux/azuredeploy.pipelinepars.json'\n        overrideParameters: '-adminUsername \"$(adminUser)\" -adminPassword \"$(adminPassword)\" -adminKey \"$(adminSSHPubKey)\" -buildTag \"$(build_id)\"'\n        deploymentMode: 'Incremental'\n  - job: DeployWindowsVMs\n    steps:\n      - task: AzureResourceManagerTemplateDeployment@3\n        displayName: Deploy Windows VM from ARM Template\n        inputs:\n          deploymentScope: 'Resource Group'\n          azureResourceManagerConnection: 'Kyle Lab Azure Subscription (eb84bcb5-ea3b-4d85-aa65-3a076739a8b2)'\n          subscriptionId: 'eb84bcb5-ea3b-4d85-aa65-3a076739a8b2'\n          action: 'Create Or Update Resource Group'\n          resourceGroupName: 'pipeline-rg'\n          location: 'East US'\n          templateLocation: 'Linked artifact'\n          csmFile: 'azure/arm_templates/101-vm-simple-windows/azuredeploy.json'\n          csmParametersFile: 'azure/arm_templates/101-vm-simple-windows/azuredeploy.json'\n          overrideParameters: '-adminUsername $(adminUser) -adminPassword $(adminPassword) -buildTag $(build_id)'\n          deploymentMode: 'Incremental'\n  - job: DeployHubToPipelinePeering\n    dependsOn: \n    - DeployLinuxVMs\n    - DeployWindowsVMs\n    steps:\n      - task: AzureResourceManagerTemplateDeployment@3\n        displayName: Deploy Hub To Pipeline Peering\n        inputs:\n          deploymentScope: 'Resource Group'\n          azureResourceManagerConnection: 'Kyle Lab Azure Subscription (eb84bcb5-ea3b-4d85-aa65-3a076739a8b2)'\n          subscriptionId: 'eb84bcb5-ea3b-4d85-aa65-3a076739a8b2'\n          action: 'Create Or Update Resource Group'\n          resourceGroupName: 'EngineeringLab'\n          location: 'East US'\n          templateLocation: 'Linked artifact'\n          csmFile: 'azure/arm_templates/vnet-peering/azuredeploy.json'\n          csmParametersFile: 'azure/arm_templates/vnet-peering/azuredeploy.hubtopipelinepars.json'\n          deploymentMode: 'Incremental'\n  - job: DeployPipelineToHubPeering\n    dependsOn: \n    - DeployLinuxVMs\n    - DeployWindowsVMs\n    - DeployHubToPipelinePeering\n    steps:\n      - task: AzureResourceManagerTemplateDeployment@3\n        displayName: Deploy Pipeline To Hub Peering\n        inputs:\n          deploymentScope: 'Resource Group'\n          azureResourceManagerConnection: 'Kyle Lab Azure Subscription (eb84bcb5-ea3b-4d85-aa65-3a076739a8b2)'\n          subscriptionId: 'eb84bcb5-ea3b-4d85-aa65-3a076739a8b2'\n          action: 'Create Or Update Resource Group'\n          resourceGroupName: 'pipeline-rg'\n          location: 'East US'\n          templateLocation: 'Linked artifact'\n          csmFile: 'azure/arm_templates/vnet-peering/azuredeploy.json'\n          csmParametersFile: 'azure/arm_templates/vnet-peering/azuredeploy.pipelinetohubpars.json'\n          deploymentMode: 'Incremental'\n- stage: DeployConfig\n  jobs:\n  - job: DeployConfigOnWindows\n    steps:\n    - script: echo Deploying config on Windows. Build ID = $build_id. Build Number = $build_number!\n      env: \n        build_id: $(Build.BuildId)\n        build_number: $(Build.BuildNumber)\n  - job: DeployConfigOnLinux\n    steps:\n    - script: echo Deploying config on Linux. Build ID = $build_id. Build Number = $build_number!\n      displayName: Test Env Vars\n      env: \n        build_id: $(Build.BuildId)\n        build_number: $(Build.BuildNumber)\n    - task: Bash@3\n      displayName: Run BASH script to make Tower API call\n      inputs:\n        targetType: 'filePath'\n        filePath: \"scripts/launch_tower_job.sh\"\n        failOnStderr: false\n        noProfile: true\n        noRc: true\n      env:\n          TEMPLATE_ID: \"$(TOWER_JOB_TEMPLATE_ID)\"\n          TOWER_USERNAME: \"$(TOWER_USERNAME)\"\n          TOWER_PASSWORD: \"$(TOWER_PASSWORD)\"\n          TOWER_URL: \"$(TOWER_URL)\"\n          HOST_FILTER: \"BuildID_$(Build.BuildNumber)\"\n- stage: DeployApplication\n  jobs:\n  - job: Deploy\n    steps:\n    - script: echo Deploying the code!\n- stage: TestAndValidate\n  jobs:\n  - job: Deploy\n    steps:\n    - script: echo Deploying the code!\n"
    }
}


[Trace - 6:55:50 AM] Sending notification 'json/schemaAssociations'.
Params: [
    {
        "fileMatch": [
            "/.condarc"
        ],
        "uri": "file:///Users/kyle/.config/coc/extensions/node_modules/coc-python/schemas/condarc.json"
    },
    {
        "fileMatch": [
            "/environment.yml"
        ],
        "uri": "file:///Users/kyle/.config/coc/extensions/node_modules/coc-python/schemas/conda-environment.json"
    },
    {
        "fileMatch": [
            "/meta.yaml"
        ],
        "uri": "file:///Users/kyle/.config/coc/extensions/node_modules/coc-python/schemas/conda-meta.json"
    }
]


[Trace - 6:55:50 AM] Sending notification 'yaml/registerCustomSchemaRequest'.
No parameters provided.


[Trace - 6:55:50 AM] Sending notification 'yaml/registerVSCodeContentRequest'.
No parameters provided.


[Trace - 6:55:50 AM] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "8465fe9d-cb3f-433d-8d46-a4f8f74c1219",
            "method": "workspace/didChangeWorkspaceFolders",
            "registerOptions": {}
        }
    ]
}


[Trace - 6:55:50 AM] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
No result returned.


[Trace - 6:55:50 AM] Received request 'custom/schema/request - (1)'.
Params: "file:///Users/kyle/Worldcom%20Exchange%20Inc/Parexel%20-%20Ansible%20Project%201839/paraxel_lab_ansible/azure-pipelines.yml"


[Trace - 6:55:50 AM] Sending response 'custom/schema/request - (1)'. Processing request took 0ms
Result: []


[Trace - 6:55:50 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/kyle/Worldcom%20Exchange%20Inc/Parexel%20-%20Ansible%20Project%201839/paraxel_lab_ansible/azure-pipelines.yml",
    "diagnostics": []
}


[Trace - 6:55:50 AM] Received request 'custom/schema/request - (2)'.
Params: "file:///Users/kyle/Worldcom%20Exchange%20Inc/Parexel%20-%20Ansible%20Project%201839/paraxel_lab_ansible/azure-pipelines.yml"


[Trace - 6:55:50 AM] Sending response 'custom/schema/request - (2)'. Processing request took 0ms
Result: []


[Trace - 6:55:51 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/kyle/Worldcom%20Exchange%20Inc/Parexel%20-%20Ansible%20Project%201839/paraxel_lab_ansible/azure-pipelines.yml",
    "diagnostics": []
}
```

Here is all the relevant version info:

Vim:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  7 2020 18:05:08)
macOS version
Included patches: 1-1719
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +clientserver      +diff              +folding           +lambda            +mouseshape        +netbeans_intg     +python3           -sun_workshop      +timers            +wildignore
+arabic            +clipboard         +digraphs          -footer            +langmap           +mouse_dec         +num64             +quickfix          +syntax            +title             +wildmenu
+autocmd           +cmdline_compl     +dnd               +fork()            +libcall           -mouse_gpm         +odbeditor         +reltime           +tag_binary        +toolbar           +windows
+autochdir         +cmdline_hist      -ebcdic            +fullscreen        +linebreak         -mouse_jsbterm     +packages          +rightleft         -tag_old_static    +transparency      +writebackup
-autoservername    +cmdline_info      +emacs_tags        +gettext           +lispindent        +mouse_netterm     +path_extra        +ruby              -tag_any_white     +user_commands     -X11
+balloon_eval      +comments          +eval              -hangul_input      +listcmds          +mouse_sgr         +perl              +scrollbind        +tcl               +vartabs           -xfontset
+balloon_eval_term +conceal           +ex_extra          +iconv             +localmap          -mouse_sysmouse    +persistent_undo   +signs             +termguicolors     +vertsplit         +xim
+browse            +cryptv            +extra_search      +insert_expand     +lua               +mouse_urxvt       +popupwin          +smartindent       +terminal          +virtualedit       -xpm
++builtin_terms    +cscope            -farsi             +ipv6              +menu              +mouse_xterm       +postscript        -sound             +terminfo          +visual            -xsmp
+byte_offset       +cursorbind        +file_in_path      +job               +mksession         +multi_byte        +printer           +spell             +termresponse      +visualextra       -xterm_clipboard
+channel           +cursorshape       +find_in_path      +jumplist          +modify_fname      +multi_lang        +profile           +startuptime       +textobjects       +viminfo           -xterm_save
+cindent           +dialog_con_gui    +float             +keymap            +mouse             -mzscheme          -python            +statusline        +textprop          +vreplace
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/liby
aml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv /usr/local/lib/libintl.a -framework AppKit  -L/usr/local/opt/l
ua/lib -llua5.3 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -frame
work CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -lruby.2.7
```

coc.nvim:

```
## versions

vim version: VIM - Vi IMproved 8.2 8021719
node version: v10.15.3
coc.nvim version: 0.0.80-1e2652e725
coc.nvim directory: /Users/kyle/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

Coc-extensions:

```
coc-json 1.3.2 ~/.config/coc/extensions/node_modules/coc-json
coc-python 1.2.13 ~/.config/coc/extensions/node_modules/coc-python
coc-snippets 2.3.1 ~/.config/coc/extensions/node_modules/coc-snippets
coc-yaml 1.3.0 ~/.config/coc/extensions/node_modules/coc-yaml
```

Any help is appreciated. Thanks!
